name: alpine-builder

on:
  push:
    branches:
      - master
    paths:
      - "alpine/Dockerfile"
      - ".github/workflows/alpine-builder.yml"
  workflow_dispatch:

jobs:
  call-image-builder:
    name: 调用构建镜像的可复用工作流
    uses: onedb-image/image-builder/.github/workflows/call-image-builder.yml@master
    secrets: inherit
    with:
      context: alpine
      tags: |
        wangdongbing/alpine:latest
        wangdongbing/alpine:3.20.2
        wangdongbing/alpine:3.20
        wangdongbing/alpine:3
