name: build-frps

on:
  push:
    branches:
      - master
    paths:
      - "frps/Dockerfile"
      - ".github/workflows/build-frps.yml"
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    uses: onedongbing/gh-actions/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      context: frps
      tags: |
        wangdongbing/frps:latest
        wangdongbing/frps:0.60.0
        wangdongbing/frps:0.60
        wangdongbing/frps:0
