name: build-v2ray

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
  push:
    paths:
      - "v2ray/v2ray.sh"
      - "v2ray/Dockerfile"
      - ".github/workflows/build-v2ray.yml"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.result.outputs.docker_tag }}
      docker_is_push: ${{ steps.result.outputs.docker_is_push }}
    steps:
      - name: Get tag to build
        id: tag
        run: |
          latest_tag=$(curl -sSL --retry 5 "https://api.github.com/repos/v2fly/v2ray-core/releases/latest" | jq .tag_name | awk -F '"' '{print $2}')
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo "Use the latest release tag of v2ray-core: ${latest_tag}"
            echo "tag=${latest_tag}" >> $GITHUB_OUTPUT
          else
            echo "Use tag: ${{ github.event.inputs.tag }}"
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Determine whether to push to DockerHub
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "PUSH=true" >> $GITHUB_ENV

      - name: Prepare environment variables
        id: result
        run: |
          echo "docker_tag=${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
          echo "docker_is_push=${PUSH:-false}" >> $GITHUB_OUTPUT

  build-image:
    name: Build Image
    needs: prepare
    uses: onedongbing/gh-actions/.github/workflows/build-image.yml@master
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      context: v2ray
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      push: true
      tags: |
        wangdongbing/v2ray-core:${{ needs.prepare.outputs.docker_tag }}
        wangdongbing/v2ray-core:latest
      build-args: TAG=${{ needs.prepare.outputs.docker_tag }}
