name: build-alpine

on:
  push:
    branches:
      - master
    paths:
      - "alpine/Dockerfile"
      - ".github/workflows/build-alpine.yml"
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    uses: onedongbing/gh-actions/.github/workflows/build-image.yml@master
    secrets: inherit
    with:
      context: alpine
      tags: |
        wangdongbing/alpine:latest
        wangdongbing/alpine:3.20.2
        wangdongbing/alpine:3.20
        wangdongbing/alpine:3
