name: build-frpc

on:
  push:
    branches:
      - master
    paths:
      - "frpc/Dockerfile"
      - ".github/workflows/build-frpc.yml"
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    uses: onedongbing/gh-actions/.github/workflows/build-image.yml@master
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      context: frpc
      tags: |
        wangdongbing/frpc:latest
        wangdongbing/frpc:0.60.0
        wangdongbing/frpc:0.60
        wangdongbing/frpc:0
