name: frpc-builder

on:
  push:
    branches:
      - master
    paths:
      - "frpc/Dockerfile"
      - ".github/workflows/frpc-builder.yml"
  workflow_dispatch:

jobs:
  call-image-builder:
    name: 调用构建镜像的可复用工作流
    uses: onedb-image/image-builder/.github/workflows/call-image-builder.yml@master
    secrets: inherit
    with:
      context: frpc
      tags: |
        wangdongbing/frpc:latest
        wangdongbing/frpc:0.60.0
        wangdongbing/frpc:0.60
        wangdongbing/frpc:0
