name: frps-builder

on:
  push:
    branches:
      - master
    paths:
      - "frps/Dockerfile"
      - ".github/workflows/frps-builder.yml"
  workflow_dispatch:

jobs:
  call-image-builder:
    name: 调用构建镜像的可复用工作流
    uses: onedb-image/image-builder/.github/workflows/call-image-builder.yml@master
    secrets: inherit
    with:
      context: frps
      tags: |
        wangdongbing/frps:latest
        wangdongbing/frps:0.60.0
        wangdongbing/frps:0.60
        wangdongbing/frps:0
